INSERT INTO Preferences (uid, food_preference, price_preference, notif_preference)
VALUES
    (00001, 'Vegetarian and Gluten Free', 'Paid, no food points', 'Often'),
    (00002, 'No Preference', 'Paid, food points', 'Often'),
    (00003, 'Gluten Free', 'Paid, food points', 'Never'),
    (00004, 'Vegan', 'Free', 'Never'),
    (00005, 'Vegetarian and Gluten Free', 'Paid, food points', 'Never'),
    (00006, 'Gluten Free', 'Free', 'Sometimes'),
    (00007, 'Vegetarian', 'Paid, food points', 'Sometimes'),
    (00008, 'Gluten Free', 'Free', 'Often'),
    (00009, 'Vegan and Gluten Free', 'Paid, food points', 'Often'),
    (00010, 'Vegan', 'Paid, food points', 'Sometimes'),
    (00011, 'No Preference', 'Paid, no food points', 'Often'),
    (00012, 'Vegan and Gluten Free', 'Free', 'Often'),
    (00013, 'Vegetarian', 'Paid, no food points', 'Sometimes'),
    (00014, 'Gluten Free', 'Paid, food points', 'Often'),
    (00015, 'No Preference', 'Paid, food points', 'Sometimes'),
    (00016, 'Vegan', 'Paid, no food points', 'Never'),
    (00017, 'Vegetarian and Gluten Free', 'Free', 'Often'),
    (00018, 'No Preference', 'Paid, no food points', 'Often'),
    (00019, 'Vegan and Gluten Free', 'Paid, food points', 'Never'),
    (00020, 'Vegetarian', 'Free', 'Sometimes'),
    (00021, 'Vegetarian', 'Paid, food points', 'Sometimes'),
    (00022, 'No Preference', 'Free', 'Often'),
    (00023, 'Vegan', 'Paid, food points', 'Often'),
    (00024, 'Gluten Free', 'Paid, no food points', 'Sometimes'),
    (00025, 'Vegetarian and Gluten Free', 'Free', 'Never'),
    (00026, 'No Preference', 'Paid, no food points', 'Sometimes'),
    (00027, 'Vegan', 'Free', 'Often'),
    (00028, 'Vegan and Gluten Free', 'Paid, food points', 'Often'),
    (00029, 'Gluten Free', 'Paid, no food points', 'Never'),
    (00030, 'Vegetarian', 'Free', 'Never'),
    (00031, 'No Preference', 'Paid, food points', 'Sometimes'),
    (00032, 'Vegan', 'Paid, no food points', 'Often'),
    (00033, 'Vegetarian and Gluten Free', 'Paid, no food points', 'Often'),
    (00034, 'No Preference', 'Paid, food points', 'Sometimes'),
    (00035, 'Vegan', 'Free', 'Never'),
    (00036, 'Vegetarian and Gluten Free', 'Paid, no food points', 'Often'),
    (00037, 'Gluten Free', 'Paid, no food points', 'Never'),
    (00038, 'No Preference', 'Free', 'Sometimes'),
    (00039, 'Vegan', 'Paid, food points', 'Often'),
    (00040, 'Vegetarian', 'Paid, food points', 'Sometimes'),
    (00041, 'No Preference', 'Free', 'Often'),
    (00042, 'Vegan', 'Paid, no food points', 'Never'),
    (00043, 'Gluten Free', 'Paid, food points', 'Sometimes'),
    (00044, 'Vegetarian and Gluten Free', 'Free', 'Never'),
    (00045, 'No Preference', 'Paid, food points', 'Often'),
    (00046, 'Vegan', 'Paid, no food points', 'Often'),
    (00047, 'Vegan and Gluten Free', 'Paid, no food points', 'Never'),
    (00048, 'No Preference', 'Paid, food points', 'Sometimes'),
    (00049, 'Vegan', 'Free', 'Sometimes'),
    (00050, 'Vegetarian and Gluten Free', 'Paid, food points', 'Often'),
    (00051, 'No Preference', 'Paid, no food points', 'Sometimes'),
    (00052, 'Vegan', 'Free', 'Often'),
    (00053, 'Vegetarian', 'Paid, food points', 'Often'),
    (00054, 'No Preference', 'Paid, no food points', 'Sometimes'),
    (00055, 'Vegan', 'Paid, food points', 'Never'),
    (00056, 'Vegetarian and Gluten Free', 'Free', 'Often'),
    (00057, 'No Preference', 'Paid, food points', 'Often'),
    (00058, 'Vegan', 'Paid, no food points', 'Sometimes'),
    (00059, 'Vegetarian', 'Free', 'Often'),
    (00060, 'No Preference', 'Paid, no food points', 'Often'),
    (00061, 'Vegan', 'Paid, food points', 'Sometimes'),
    (00062, 'Vegetarian and Gluten Free', 'Paid, food points', 'Often'),
    (00063, 'No Preference', 'Paid, no food points', 'Often'),
    (00064, 'Vegan', 'Free', 'Sometimes'),
    (00065, 'Vegetarian and Gluten Free', 'Paid, food points', 'Never'),
    (00066, 'No Preference', 'Paid, no food points', 'Sometimes'),
    (00067, 'Vegan', 'Paid, no food points', 'Often'),
    (00068, 'Vegetarian', 'Free', 'Often'),
    (00069, 'No Preference', 'Paid, food points', 'Sometimes'),
    (00070, 'Vegan', 'Paid, no food points', 'Often'),
    (00071, 'Vegetarian and Gluten Free', 'Free', 'Sometimes'),
    (00072, 'No Preference', 'Paid, food points', 'Often'),
    (00073, 'Vegan', 'Paid, no food points', 'Never'),
    (00074, 'Vegetarian', 'Paid, food points', 'Sometimes'),
    (00075, 'No Preference', 'Free', 'Often'),
    (00076, 'Vegan', 'Paid, food points', 'Often'),
    (00077, 'Vegetarian and Gluten Free', 'Paid, food points', 'Never'),
    (00078, 'No Preference', 'Paid, no food points', 'Sometimes'),
    (00079, 'Vegan', 'Free', 'Often'),
    (00080, 'Vegetarian', 'Paid, food points', 'Often'),
    (00081, 'No Preference', 'Paid, food points', 'Sometimes'),
    (00082, 'Vegan', 'Free', 'Often'),
    (00083, 'Vegetarian and Gluten Free', 'Paid, no food points', 'Never'),
    (00084, 'No Preference', 'Paid, no food points', 'Sometimes'),
    (00085, 'Vegan', 'Paid, food points', 'Often'),
    (00086, 'Vegetarian', 'Free', 'Often'),
    (00087, 'No Preference', 'Paid, food points', 'Sometimes'),
    (00088, 'Vegan', 'Paid, no food points', 'Often'),
    (00089, 'Vegetarian and Gluten Free', 'Free', 'Sometimes'),
    (00090, 'No Preference', 'Paid, food points', 'Often'),
    (00091, 'Vegan', 'Paid, no food points', 'Often'),
    (00092, 'Vegetarian', 'Paid, food points', 'Sometimes'),
    (00093, 'No Preference', 'Free', 'Sometimes'),
    (00094, 'Vegan', 'Paid, no food points', 'Never'),
    (00095, 'Vegetarian and Gluten Free', 'Paid, food points', 'Often'),
    (00096, 'No Preference', 'Paid, food points', 'Often'),
    (00097, 'Vegan', 'Free', 'Sometimes'),
    (00098, 'Vegetarian', 'Paid, food points', 'Often'),
    (00099, 'No Preference', 'Paid, no food points', 'Often'),
    (00100, 'Vegan', 'Paid, food points', 'Sometimes');

